routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

Auth::routes();

	// Route::get('/home', 'HomeController@index');
Route::get('login',function(){
	return view('login.praloginpage');
});
Route::get('/','Page\IndexController@index');
Route::get('news/{id}/{url}/read','Page\IndexController@show');
Route::group(['prefix'=>'home'],function(){
	Route::get('pendaftaran','Page\PendaftaranController@index')->name('pendaftaran');
	Route::post('submit/pendaftaran','Page\PendaftaranController@store')->name('pendaftaran.submit');
	Route::get('direct','Page\PendaftaranController@direct')->name('redirect');
});

// Route::get('/admin', 'AdminController@index');
Route::group(['prefix'=>'admin'],function(){
	Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::get('/adminlogout','Auth\AdminLoginController@logout')->name('admin.logout');
	Route::post('/proseslogin','Auth\AdminLoginController@login')->name('admin.login.submit');
	// Route::get('/','AdminController@index')->name('admin.dashboard');

	Route::resources([
		'homepage'=>'Admin\HomeController',
		'atlit'=>'Admin\UsersController',
		'admin'=>'Admin\AdminController',
		'cabor'=>'Admin\CaborController',
		'prestasi'=>'Admin\PrestasiController',
		'visimisi'=>'Admin\VisiMisiController',
		'sejarah'=>'Admin\SejarahController',
		'caborprestasi'=>'Admin\CaborPrestasiController',
		'berita'=>'Admin\BeritaController',
		'pelatih'=>'Admin\PelatihController',
		'tahun'=>'Admin\TahunController',
		'pertandingan'=>'Admin\PertandinganController',
		'listatlitlomba'=>'Admin\ListAtlitLombaController',
		'madin'=>'Admin\MadinController',
		'medali'=>'Admin\MedaliController',
		'regu'=>'Admin\ReguController',
		'reguprestasi'=>'Admin\ReguPrestasiController',
		'pengumumanadmin'=>'Admin\PengumumanController',
		
		]);
	Route::get('datatables','Admin\CaborController@anyData')->name('datatables.data');
	Route::get('atlitTable','Admin\UsersController@atlit')->name('atlit.data');
	
});

Route::group(['prefix'=>'atlit'],function(){
	Route::get('page-login','User\UserloginController@FormLogin')->name('user.login');
	Route::post('proses-login','User\UserloginController@proses')->name('user.proses.submit');
	Route::get('userlogout','User\UserloginController@logout')->name('user.out');

	Route::resources([
		'home'=>'User\HomeController',
		'profile'=>'User\ProfileSelfController',
		'cabangolah'=>'User\CaborController',
		'user'=>'User\AtlitController',
		'notif'=>'User\NotifController',
		'pengumuman'=>'User\PengumumanController',
		]);
});



Route::get('pelatih/login','Pelatih\PelatihLoginController@form')->name('pelatih.login');
Route::post('pelatih/proseslogin','Pelatih\PelatihLoginController@proses')->name('pelatih.proses');
Route::get('pelatih/proseslogout','Pelatih\PelatihLoginController@logout')->name('pelatih.logout');

Route::group(['prefix'=>'pelatih','middleware'=>'auth:pelatih'],function(){
	Route::get('atlitbinaan','Pelatih\AtlitController@mine');	
	Route::get('landing','Pelatih\HomeController@index');
	Route::get('allatlit','Pelatih\AtlitController@all');
	Route::get('calonatlit','Pelatih\AcceptAtlitController@index');
	Route::get('calonatlit/{id}','Pelatih\AcceptAtlitController@show')->name('select.atlit');
	Route::get('downloadfileatlit/{id}','Pelatih\AcceptAtlitController@download')->name('download.atlit');
	Route::get('accept/{id}/atlit','Pelatih\AcceptAtlitController@accept')->name('accept.atlit');
	Route::get('reject/{id}/atlit','Pelatih\AcceptAtlitController@reject')->name('reject.atlit');
	Route::get('selectatlit/{id}','Pelatih\SelectAtlitController@pertandingan');
	Route::get('atlitpertandingan','Pelatih\SelectAtlitController@index');
	Route::post('selectatlit/{id}/save','Pelatih\SelectAtlitController@store')->name('pertandinganatlit.store');
	Route::delete('delete/{id}/choice','Pelatih\SelectAtlitController@destroy')->name('choice.delete');

	Route::resources([
		'pengumuman'=>'Pelatih\PengumumanController',

		]);


});



Route::post('drop','DropdownController@dropdown');

Route::get('grafik/jumlahcatlit','Page\GrafikController@grafik')->name('cabor.user');
Route::get('grafik/umur','Page\GrafikController@byAge')->name('grafik.umur');
Route::get('grafik/medali','Page\GrafikController@bypiala')->name('grafik.piala');
Route::get('grafik/pelatih','Page\GrafikController@pelatih')->name('grafik.pelatih');

Route::get('visimisi/sejarah','Page\IndexController@visimisi')->name('koni.visimisi');
Route::get('allnews','Page\IndexController@allnews')->name('all.news');
Route::get('pengumuman','Page\IndexController@pengumuman')->name('all.pengumuman');
Route::get('pengumuman/{id}/{url}/read','Page\IndexController@readpengumuman')->name('pengumuman.read');
Route::get('bank','Page\IndexController@bank')->name('bank.data');

Route::get('t',function(){
	return App\User::first()->cabor;
	
});

app/Http/Controllers/Admin/PelatihController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Pelatih;
use App\Model\Provinsi;
use App\Model\Cabor;
use Hash,File,Session;

class PelatihController extends Controller
{
    public function __construct(Pelatih $pelatih,Provinsi $provinsi,Cabor $cabor){
    	$this->pelatih=$pelatih;
    	$this->provinsi=$provinsi;
    	$this->cabor=$cabor;
    	$this->middleware('auth:admin');
    }
    public function index(Request $request){
        $pelatih=$this->pelatih->orderBy('id','desc')->filter($request)->paginate(30);
        $cabor=$this->cabor->all()->pluck('nama_cabor','id');
        return view('Admin.pelatih.index',compact('pelatih','cabor'));
    }

    public function create(){    	
    	$provinsi=$this->provinsi->all()->pluck('nama_provinsi','id');
    	$cabor=$this->cabor->all()->pluck('nama_cabor','id');
    	return view('Admin.pelatih.tambah',compact('provinsi','cabor'));
    }
    public function store(Request $request){
    	$this->validate($request,[
    		'nama'=>'required',
    		'email'=>'required|email',
    		'password'=>'required|min:6|max:20',
    		'gambar'=>'required|mimes:JPG,JPEG,PNG,jpg,jpeg,png',
    		'alamat_rinci'=>'required',
    		'tgl_lahir'=>'required|date|before:today',
    		'pelatih_id'=>'required',
    		'kelamin'=>'required',
    		'provinsi_id'=>'required',
    		'kabupaten_id'=>'required',
    		'kota_id'=>'required',
    		'kecamatan_id'=>'required',
    		'kelurahan_id'=>'required',
    		'no_hp'=>'required',
    		'agama'=>'required',
    		]);
    	$pelatih=$request->all();
    	$pelatih['password']=Hash::make($request->password);
    	if ($request->hasFile('gambar')) {
    		$file=$request->file('gambar');
    		$direktori=public_path().'/gambar/pelatih/';
    		$nama_file=str_random(20).'.'.$file->getClientOriginalExtension();
    		$uploadSuccess=$file->move($direktori,$nama_file);
    		$pelatih['gambar']=$nama_file;
    	}
    
    	$this->pelatih->create($pelatih);
        Session::flash('message','data berhasil disimpan');
        return redirect('admin/pelatih');
    }

    public function edit($id){
        $pelatih=$this->pelatih->find($id);
        $cabor=$this->cabor->all()->pluck('nama_cabor','id');
        $provinsi=$this->provinsi->all()->pluck('nama_provinsi','id');
        return view('Admin.pelatih.ubah',compact('pelatih','cabor','provinsi'));
    }

    public function update($id,Request $request){
        $region=$this->pelatih->find($id);
        $this->validate($request,[
            'nama'=>'required',
            'email'=>'required|email',
            
            'gambar'=>'mimes:JPG,JPEG,PNG,jpg,jpeg,png',
            'alamat_rinci'=>'required',
            'tgl_lahir'=>'required|date|before:today',
            'pelatih_id'=>'required',
            'kelamin'=>'required',
            'provinsi_id'=>'required',
            
            'no_hp'=>'required',
            'agama'=>'required',
            ]);
        $pelatih=$request->all();
        if ($request->hasFile('gambar')) {
            $file=$request->file('gambar');
            $direktori=public_path().'/gambar/pelatih/';
            File::delete($direktori.$this->pelatih->find($id)->gambar);            
            $nama_file=str_random(20).'.'.$file->getClientOriginalExtension();
            $uploadSuccess=$file->move($direktori,$nama_file);
            $pelatih['gambar']=$nama_file; 
        }else{
            $pelatih['gambar']=$this->pelatih->find($id)->gambar;
        }

        if ($request->has('password')) {
            $pelatih['password']=Hash::make($request->password);
        }else{
            $pelatih['password']=$this->pelatih->find($id)->password;
        }

        if ($request->has('kabupaten_id')) {
            $pelatih['kabupaten_id']=$request->kabupaten_id;
        }else{
            $pelatih['kabupaten_id']=$region->kabupaten_id;
        }
        if ($request->has('kota_id')) {
            $pelatih['kota_id']=$request->kota_id;
        }else{
            $pelatih['kota_id']=$region->kota_id;
        }
        if ($request->has('kecamatan_id')) {
            $pelatih['kecamatan_id']=$request->kecamatan_id;
        }else{
            $pelatih['kecamatan_id']=$region->kecamatan_id;
        }
        if ($request->has('kelurahan_id')) {
            $pelatih['kelurahan_id']=$request->kelurahan_id;
        }else{
            $pelatih['kelurahan_id']=$region->kelurahan_id;
        }

        $this->pelatih->find($id)->update($pelatih);
       Session::flash('message','data berhasil disimpan');
        return redirect('admin/pelatih');
    }

    public function destroy($id){
        $this->pelatih->destroy($id);
        Session::flash('message','data berhasil dihapus');
        return redirect('admin/pelatih');
    }
}

app/Http/Controllers/Admin/PengumumanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\PengumumanAdmin;
use Session;
class PengumumanController extends Controller
{

    public function __construct(PengumumanAdmin $pengumuman){
        $this->middleware('auth:admin');
        $this->pengumuman=$pengumuman;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengumuman=$this->pengumuman->orderBy('id','desc')->paginate(20);
        return view('Admin.pengumuman.index',compact('pengumuman'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.pengumuman.tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
        ]);
        $pengumuman=$request->all();
        $url=str_replace(' ','-', $request->judul);
        $pengumuman['url']=str_replace('/','-',$url).'.html';
        $this->pengumuman->create($pengumuman);
        Session::flash('message','pengumuman berhasil dibuat');
        return redirect('admin/pengumumanadmin');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengumuman=$this->pengumuman->findOrFail($id);
         return view('Admin.pengumuman.ubah',compact('pengumuman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
        ]);
        $pengumuman=$request->all();
        $url=str_replace(' ','-', $request->judul);
        $pengumuman['url']=str_replace('/','-',$url).'.html';
        $this->pengumuman->find($id)->update($pengumuman);
        Session::flash('message','pengumuman berhasil diubah');
        return redirect('admin/pengumumanadmin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->pengumuman->destroy($id);
          Session::flash('message','pengumuman berhasil dihapus');
        return redirect('admin/pengumumanadmin');
    }
}

app/Http/Controllers/Pelatih/AcceptAtlitController.php
<?php

namespace App\Http\Controllers\Pelatih;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Session;
use App\Model\Notif;
use Auth;
class AcceptAtlitController extends Controller
{
    public function __construct(User $atlit){
    	$this->atlit=$atlit;
    }

    public function index(){
    	$atlit=$this->atlit->where(['status'=>'waiting'])->orderBy('id','desc')->paginate(20); 
      
    	return view('Pelatih.Calonatlit.index',compact('atlit'));
    }

    public function show($id){
    	$atlit=$this->atlit->find($id);
    	return view('Pelatih.Calonatlit.showatlit',compact('atlit'));
    }
    public function download($id){
    	$atlit=$this->atlit->findOrFail($id);    	    	
    	if (empty($atlit->sertifikat->nama_sertifikat)){
    		return response(404);
    	}elseif(!empty($atlit->sertifikat->nama_sertifikat)){
    		return response()->download(public_path().'/file/sertifikat/'.$atlit->sertifikat->nama_sertifikat);
    	}
    }

    public function accept($id){
    	$atlit= User::findOrFail($id);
    	$atlit->status='accepted';
    	$atlit->update();

    	$notif= new Notif;
    	$notif->isi='Selamat anda berhasil diterima sebagai atlit '.$atlit->cabor->nama_cabor.' di koni kaltim silahkan hubungi pelatih anda '.Auth::user()->nama.'  '.Auth::user()->email.' untuk mendapatkan update informasi terbaru, pemeritahuan lain dapat anda lihat pada menu pengumuman';
    	$notif->user_id=$atlit->id;
    	$notif->pelatih_id=Auth::user()->id;
    	$notif->status='belum';
    	$notif->save();
    	Session::flash('message','atlit telah anda terima,');
    	return redirect()->back();
    	
    }

    public function reject($id){
        $atlit= User::findOrFail($id);
        $atlit->status='rejected';
        $atlit->update();

        $notif= new Notif;
        $notif->isi='Mohon maaf anda belum diterima sebagai atlit '.$atlit->cabor->nama_cabor.' di koni kaltim, silahkan mencoba dilain waktu';
        $notif->user_id=$atlit->id;
        $notif->pelatih_id=Auth::user()->id;
        $notif->status='belum';
        $notif->save();
        Session::flash('message','atlit telah anda tolak,');
        return redirect()->back();
    }
}

app/Http/Controllers/Pelatih/AddLombaController.php
<?php

namespace App\Http\Controllers\Pelatih;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\AtlitPertandingan;
class AddLombaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Pelatih/AtlitController.php
<?php

namespace App\Http\Controllers\Pelatih;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;	
use Auth;
class AtlitController extends Controller
{
	public function __construct(User $atlit){
		$this->atlit=$atlit;
	}
    public function mine(){
    	$atlit=$this->atlit->where('olahraga_id',Auth::user()->pelatih_id)->where('status','accepted')->orderBy('id','desc')->paginate(20);
    	return view('Pelatih.AtlitBinaan.index',compact('atlit'));
    }

    public function all(){
    	$atlit=$this->atlit->where('status','accepted')->orderBy('id','desc')->paginate(20);
    	return view('Pelatih.Atlit.index',compact('atlit'));
    }
}

resources/views/Pelatih/pengumuman/form.blade.php
<fieldset> 
    <div class="row"> 
        <div class="col-lg-12">
             <div class="form-group">
                {!! Form::label('Judul','Judul') !!}
                {!! Form::text('judul',null,['class'=>'form-control'])!!}  
                {!! $errors->first('judul', '<dt style="font-family:verdana;color:red;"><i class="fa fa-times"></i>:message</dt>') !!}    
            </div>      
        </div> 
        
        <div class="col-lg-10">      
            <div class="form-group">
            {!! Form::label('Isi','Isi') !!}
            {!! Form::textarea('isi',null,['class'=>'fr-view'])!!}  
            {!! $errors->first('isi', '<dt style="font-family:verdana;color:red;"><i class="fa fa-times"></i>:message</dt>') !!}    
        </div>       
            
         </div>
         
         <div class="col-lg-12">
            
             {!!Form::submit('Simpan',['class'=>'btn btn-primary']) !!} 
         </div>
     </div>
 </fieldset>

resources/views/Pelatih/pengumuman/index.blade.php
@extends('template.pelatih.template-pelatih')
@section("content")

<div class="row">
	<div class="col-md-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Data pengumuman</h5>

				<div class="ibox-tools">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-wrench"></i>
					</a>
					<ul class="dropdown-menu dropdown-user">
						<li><a href="#">Config option 1</a>
						</li>
						<li><a href="#">Config option 2</a>
						</li>
					</ul>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
			<div class="ibox-content">
			<div>
			<a href="{{route('pengumuman.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i>	Tambah data</a>
			</div>
					@if(Session::has('message'))
					<div class="alert alert-success alert-dismissable">
						
						<dt style="font-family:verdana;"><i class="fa fa-check"></i>	{{Session::get('message')}}</dt>
		
					</div>  
					@endif

				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
						<?php  $no=1; ?>
							<tr>
								<th>No</th>
								<th>Judul pengumuman</th>								
								<th>Isi</th>
								<th>Aksi</th>
							</tr>
						</thead>
						<tbody>
							
							@foreach($pengumuman as $skefo)
							<tr class="gradeC">
								<td>{{$loop->iteration}}</td>
								<td>{{$skefo->judul}}</td>							 
								<td><a class="btn btn-primary" data-toggle="modal" data-target="#myModal2{{$skefo->id}}"><i class="fa fa-tasks"></i> Show</a></td>
								<td>
									{!! Form::open(['route'=>['pengumuman.destroy',$skefo->id],'method'=>'delete','onsubmit'=>'return confirm("Yakin Ingin Menghapus?")'])!!}
									<a class="btn btn-warning" href="{{route('pengumuman.edit',$skefo->id)}}"><i class="fa fa-pencil"></i>	Ubah</a>
									<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i>	Hapus</button>
									{!! Form::close()!!}
								</td>				
								
							</tr>
			
            
               <!-- modal text -->
              <div class="modal inmodal fade" id="myModal2{{$skefo->id}}" tabindex="-1" role="dialog"  aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        
                          <small class="font-bold"></small>
                        </div>
                        <div class="modal-body">
                          {!! $skefo->isi !!}
                        </div>

                        <div class="modal-footer">
                          <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                      </div>
                    </div>
                  </div>
              <!-- endmodal text-->
              		
              		
					@endforeach()
						</tbody>
						<tfoot>
							<tr>
								<th>No</th>
								<th>Judul pengumuman</th>								
								<th>Isi</th>
								<th>Aksi</th>
							</tr>
						</tfoot>
					</table>
					
				</div>
				{!! $pengumuman->render() !!}
			</div>
		</div>
	</div>
</div>



			@stop()

resources/views/Pelatih/pengumuman/tambah.blade.php
@extends('template.pelatih.template-pelatih')
@section('content')
 

	<div class="col-lg-12">
		<div class="ibox">
			<div class="ibox-title">
				<h5>Tambah Data pengumuman</h5>
				<div class="ibox-tools">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-wrench"></i>
					</a>
					
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
		
			<div class="ibox-content">
				 

				{!! Form::open(['route'=>'pengumuman.store','method'=>'post','class'=>'wizard-big','enctype=multipart/form-data']) !!}

					@include('Pelatih.pengumuman.form')

				{!! Form::close() !!}

			</div>
		</div>
	</div>



@stop

resources/views/Pelatih/pengumuman/ubah.blade.php
@extends('template.pelatih.template-pelatih')
@section('content')
  
<div class="row">
	<div class="col-lg-12">
		<div class="ibox">
			<div class="ibox-title">
				<h5>Ubah Data pengumuman</h5>
				<div class="ibox-tools">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-wrench"></i>
					</a>
					
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
	

			<div class="ibox-content">
				 

				{!! Form::model($pengumuman,['route'=>['pengumuman.update',$pengumuman->id],'method'=>'put','class'=>'wizard-big','enctype'=>'multipart/form-data']) !!}

					@include('Pelatih.pengumuman.form')

				{!! Form::close() !!}

			</div>
		</div>
	</div>

</div>


@stop